/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
//Stuff removed from game
ServerEvents.recipes(catalyst => {
    catalyst.remove('ae2:network/blocks/spatial_anchor')
    catalyst.remove('reliquary:alkahestry_tome')
    catalyst.remove('mekanism:dimensional_stabilizer')
    catalyst.remove('mekanism:upgrade_anchor')
    catalyst.remove("sophisticatedbackpacks:stack_upgrade_omega_tier")
    catalyst.remove("sophisticatedbackpacks:inception_upgrade")
    catalyst.remove("sophisticatedstorage:stack_upgrade_omega_tier")
    catalyst.remove({output: "sophisticatedstorage:stack_upgrade_omega_tier"})
    catalyst.remove({output: "extendedae:circuit_cutter"})
    catalyst.remove({output: "waystones:white_portstone"})
    catalyst.remove({output: "waystones:orange_portstone"})
    catalyst.remove({output: "waystones:magenta_portstone"})
    catalyst.remove({output: "waystones:light_blue_portstone"})
    catalyst.remove({output: "waystones:yellow_portstone"})
    catalyst.remove({output: "waystones:lime_portstone"})
    catalyst.remove({output: "waystones:pink_portstone"})
    catalyst.remove({output: "waystones:gray_portstone"})
    catalyst.remove({output: "waystones:light_gray_portstone"})
    catalyst.remove({output: "waystones:cyan_portstone"})
    catalyst.remove({output: "waystones:purple_portstone"})
    catalyst.remove({output: "waystones:blue_portstone"})
    catalyst.remove({output: "waystones:brown_portstone"})
    catalyst.remove({output: "waystones:green_portstone"})
    catalyst.remove({output: "waystones:red_portstone"})
    catalyst.remove({output: "waystones:black_portstone"})
    catalyst.remove({output: "waystones:orange_sharestone"})
    catalyst.remove({output: "waystones:magenta_sharestone"})
    catalyst.remove({output: "waystones:light_blue_sharestone"})
    catalyst.remove({output: "waystones:yellow_sharestone"})
    catalyst.remove({output: "waystones:lime_sharestone"})
    catalyst.remove({output: "waystones:pink_sharestone"})
    catalyst.remove({output: "waystones:gray_sharestone"})
    catalyst.remove({output: "waystones:light_gray_sharestone"})
    catalyst.remove({output: "waystones:cyan_sharestone"})
    catalyst.remove({output: "waystones:purple_sharestone"})
    catalyst.remove({output: "waystones:blue_sharestone"})
    catalyst.remove({output: "waystones:brown_sharestone"})
    catalyst.remove({output: "waystones:green_sharestone"})
    catalyst.remove({output: "waystones:red_sharestone"})
    catalyst.remove({output: "waystones:black_sharestone"})
    catalyst.remove({output: "waystones:warp_plate"})
    catalyst.remove({output: "waystones:dormant_shard"})
})

//Stuff that has new recipies
ServerEvents.recipes(catalyst => {
    catalyst.remove({output: "sophisticatedbackpacks:iron_backpack"})
    catalyst.remove({output: "sophisticatedbackpacks:gold_backpack"})
    catalyst.remove({output: "sophisticatedbackpacks:diamond_backpack"})
    catalyst.remove({output: "sophisticatedbackpacks:netherite_backpack"})
    catalyst.remove({output: "ae2:printed_logic_processor"})
    catalyst.remove({output: "ae2:printed_calculation_processor"})
    catalyst.remove({output: "ae2:printed_engineering_processor"})
    catalyst.remove({output: "ae2:printed_silicon"})
    catalyst.remove({output: "ae2:engineering_processor"})
    catalyst.remove({output: "ae2:calculation_processor"})
    catalyst.remove({output: "ae2:logic_processor"})
    catalyst.remove({output: "ae2:terminal"})
    catalyst.remove({output: "ae2:crafting_terminal"})
    catalyst.remove({output: "waystones:warp_stone"})
    catalyst.remove({output: "waystones:waystone"})
    catalyst.remove({output: "waystones:warp_dust"})
    catalyst.remove({output: "eternalores:ender_dust"})
    catalyst.remove({output: "waystones:sandy_waystone"})
    catalyst.remove({output: "waystones:deepslate_waystone"})
    catalyst.remove({output: "waystones:blackstone_waystone"})
    catalyst.remove({output: "waystones:end_stone_waystone"})
    catalyst.remove({id: "waystones:mossy_waystone"})

})

/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
