/* 
This script is property of Catalyst Studios for use in the Catalyst: Create. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
RecipeViewerEvents.removeEntries('item', catalyst => {
    catalyst.remove('mekanism:dimensional_stabilizer')
    catalyst.remove('mekanism:upgrade_anchor')
    catalyst.remove('ae2:network/blocks/spatial_anchor')
    catalyst.remove('reliquary:alkahestry_tome')
    catalyst.remove('sophisticatedbackpacks:stack_upgrade_omega_tier')
    catalyst.remove('sophisticatedbackpacks:inception_upgrade')
    catalyst.remove('sophisticatedstorage:stack_upgrade_omega_tier')
    catalyst.remove('extendedae:circuit_cutter')
    catalyst.remove('waystones:orange_sharestone')
    catalyst.remove('waystones:magenta_sharestone')
    catalyst.remove('waystones:light_blue_sharestone')
    catalyst.remove('waystones:yellow_sharestone')
    catalyst.remove('waystones:lime_sharestone')
    catalyst.remove('waystones:pink_sharestone')
    catalyst.remove('waystones:gray_sharestone')
    catalyst.remove('waystones:light_gray_sharestone')
    catalyst.remove('waystones:cyan_sharestone')
    catalyst.remove('waystones:purple_sharestone')
    catalyst.remove('waystones:blue_sharestone')
    catalyst.remove('waystones:brown_sharestone')
    catalyst.remove('waystones:green_sharestone')
    catalyst.remove('waystones:red_sharestone')
    catalyst.remove('waystones:black_sharestone')
    catalyst.remove('waystones:white_portstone')
    catalyst.remove('waystones:orange_portstone')
    catalyst.remove('waystones:magenta_portstone')
    catalyst.remove('waystones:light_blue_portstone')
    catalyst.remove('waystones:yellow_portstone')
    catalyst.remove('waystones:lime_portstone')
    catalyst.remove('waystones:pink_portstone')
    catalyst.remove('waystones:gray_portstone')
    catalyst.remove('waystones:light_gray_portstone')
    catalyst.remove('waystones:cyan_portstone')
    catalyst.remove('waystones:purple_portstone')
    catalyst.remove('waystones:blue_portstone')
    catalyst.remove('waystones:brown_portstone')
    catalyst.remove('waystones:green_portstone')
    catalyst.remove('waystones:red_portstone')
    catalyst.remove('waystones:black_portstone')
    catalyst.remove('waystones:warp_plate')
    catalyst.remove('waystones:dormant_shard')
    catalyst.remove('immersive_aircraft:hull')
    catalyst.remove("immersive_aircraft:hull_reinforcement")
    catalyst.remove('/ironfurnaces:upgrade/')
})
/* 
This script is property of Catalyst Studios for use in the Catalyst: Create. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/